function generateSetupReport(deployment) {


    const report = `

FLOMO SETUP SUITE
============================


Computer Setup Report


Computer Name:
${deployment.computerName}


Profile:
${deployment.profile}


Status:
${deployment.status}


Deployment Date:
${new Date(deployment.date).toLocaleString()}


============================

Generated by Flomo Setup Suite

`;



    const blob = new Blob(

        [report],

        {
            type: "text/plain"
        }

    );



    const url = URL.createObjectURL(blob);



    const link = document.createElement("a");


    link.href = url;


    link.download =
        `${deployment.computerName}-setup-report.txt`;



    link.click();



    URL.revokeObjectURL(url);


}



export default generateSetupReport;